#!/bin/bash
ls -a | find . -type f -name '*.gif' | rev | cut -d '/' -f 1 | cut -d '.' -f 2 | rev | LC_ALL=C sort -f[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D-[C[C[C[C[C[C[C[C[C[C[B[C[C[C[C[C[C[C[C[C[C[C[C[C[C
